#!/usr/bin/env python3
"""Shared data for the 21 Sanctify blog posts (used by image gen + page builder).

Facts sourced from sanctify.co: award-winning advertising & digital marketing
agency in Goa since 2012, 100+ brands. Phone/WhatsApp +91 99233 52923,
help@sanctify.in, based in Vasco-da-Gama.
"""

BRAND = {
    "name": "Sanctify",
    "phone": "+91 99233 52923",
    "tel": "+919923352923",
    "wa": "https://wa.me/919923352923",
    "email": "help@sanctify.in",
    "site": "https://www.sanctify.in/",
    "since": "2012",
}

# Image style: tasteful, professional, adult model.
IMG_BASE = ("Photorealistic editorial marketing photograph. A confident young Indian woman in her early-to-mid 20s "
            "with a friendly, professional appearance, wearing a modern western {outfit}, {scene}. "
            "Bright natural daylight, clean contemporary composition, tasteful and professional, shallow depth of field. "
            "No text, no watermark, no logo, no captions.")

def _img(outfit, scene):
    return IMG_BASE.format(outfit=outfit, scene=scene)

BLOGS = [
 # ---------- Service posts ----------
 dict(n=1, slug="seo-services-in-goa", cat="SEO", loc="Goa",
   title="SEO Services in Goa: Rank Higher & Get Found | Sanctify",
   h1="SEO Services in Goa: How to Rank Higher and Get Found",
   excerpt="Practical SEO for Goa businesses — keyword research, on-page, technical and local SEO that grows organic traffic and leads. By Sanctify, Goa's award-winning agency since 2012.",
   img_alt="Young Indian woman reviewing SEO analytics on a laptop in a bright Goa office",
   img_prompt=_img("smart-casual blazer over a top", "working on a laptop showing rising analytics graphs in a bright modern office"),
   intro=["If customers can't find you on Google, they'll find a competitor. Search engine optimization (SEO) is how Goa businesses earn steady, free traffic from people actively searching for what they sell.",
          "Sanctify has helped 100+ Goan brands climb the rankings since 2012. Here's how a results-focused SEO programme actually works — and what to expect."],
   offers=[("Keyword research","We map the exact phrases your Goa customers search, from 'best' queries to 'near me' intent."),
           ("On-page SEO","Titles, meta descriptions, headings and content optimised for both readers and search engines."),
           ("Technical SEO","Site speed, mobile-friendliness, indexing and structured data so Google can crawl and trust your site."),
           ("Content & links","Helpful pages and quality backlinks that build topical authority over time.")],
   why_h="Why SEO matters for Goa businesses",
   why="Goa's market is seasonal and competitive — tourists, locals and NRIs all search differently. Ranking for the right local and intent-driven keywords means you capture demand at the exact moment it appears, without paying for every click. Unlike ads, SEO compounds: the work you do this quarter keeps returning traffic for months.",
   process=["Audit your current rankings, site health and competitors","Build a keyword and content plan around real search demand","Fix on-page and technical issues","Publish helpful content and earn quality links","Report monthly on rankings, traffic and leads"],
   faqs=[("How long does SEO take in Goa?","Most businesses see meaningful movement in 3–6 months, with compounding gains after that. Local and low-competition terms can rank faster."),
         ("Do you guarantee #1 rankings?","No credible agency can guarantee a specific position, but we focus on measurable growth in rankings, traffic and leads with transparent monthly reporting."),
         ("Is SEO better than Google Ads?","They work best together — ads for instant leads, SEO for durable, lower-cost traffic. We often run both.")]),

 dict(n=2, slug="local-seo-google-business-profile-goa", cat="Local SEO", loc="Goa",
   title="Local SEO & Google Business Profile in Goa | Sanctify",
   h1="Local SEO & Google Business Profile: Win 'Near Me' Searches in Goa",
   excerpt="Get into the Google Map Pack for 'near me' searches across Goa with expert Google Business Profile and local SEO from Sanctify.",
   img_alt="Young Indian woman using Google Maps on a phone outside a Goa storefront",
   img_prompt=_img("smart-casual outfit", "standing outside a small storefront using a smartphone showing a map"),
   intro=["When someone searches 'salon near me' or 'best cafe in Panaji', Google shows a map with three businesses. Getting into that Map Pack is the single highest-ROI move for most local Goa businesses.",
          "Sanctify optimises your Google Business Profile and local signals so you show up first when nearby customers are ready to buy."],
   offers=[("Profile optimisation","Categories, services, hours, photos and descriptions tuned for maximum visibility."),
           ("Reviews strategy","Simple systems to earn and respond to genuine customer reviews."),
           ("Local citations","Consistent name, address and phone across directories like Goa Directory."),
           ("Map Pack targeting","On-page and local content that helps you rank for 'near me' and city searches.")],
   why_h="Why the Map Pack wins in Goa",
   why="Most clicks for local searches go to the top three map results. For restaurants, salons, clinics, rentals and shops across Goa, a well-optimised Google Business Profile often drives more calls and directions than the website itself — especially on mobile, which is how tourists and locals search on the go.",
   process=["Claim and verify your Google Business Profile","Optimise categories, services, photos and hours","Build consistent local citations","Set up a review-generation flow","Track calls, directions and Map Pack rankings"],
   faqs=[("What is the Google Map Pack?","It's the block of three local businesses shown with a map at the top of local search results — prime real estate for 'near me' queries."),
         ("How do I get more Google reviews?","We set up easy review links and QR codes, and help you respond professionally to build trust."),
         ("Do I need a website for local SEO?","It helps a lot, but a strong Google Business Profile can generate leads on its own while your site grows.")]),

 dict(n=3, slug="google-ads-ppc-goa", cat="Google Ads", loc="Goa",
   title="Google Ads (PPC) in Goa: Leads That Convert | Sanctify",
   h1="Google Ads in Goa: ROI-Focused PPC That Brings Qualified Leads",
   excerpt="ROI-focused Google Ads and PPC management in Goa — search, display and remarketing that bring qualified leads fast. By Sanctify.",
   img_alt="Young Indian woman planning a Google Ads campaign on a laptop in a Goa workspace",
   img_prompt=_img("professional blazer", "reviewing campaign performance charts on a laptop in a bright co-working space"),
   intro=["Need leads this week, not this quarter? Google Ads puts your business at the top of search the moment someone looks for what you offer — and you only pay when they click.",
          "Sanctify runs ROI-focused paid campaigns for Goa businesses, tuned to bring qualified enquiries without wasting budget."],
   offers=[("Search ads","Capture high-intent 'ready to buy' searches across Goa."),
           ("Display & YouTube","Reach the right audiences with visual and video placements."),
           ("Remarketing","Bring back visitors who didn't convert the first time."),
           ("Conversion tracking","Every rupee measured against calls, forms and sales.")],
   why_h="Why PPC works for Goa's seasonal market",
   why="Goa's demand spikes around seasons, events and weekends. Paid ads let you scale up instantly when demand is high and pause when it's not — perfect for hotels, rentals, events and services. With tight targeting and conversion tracking, you know exactly what each lead costs.",
   process=["Define goals and target cost-per-lead","Research keywords and audiences","Build tightly-themed campaigns and landing pages","Launch, then optimise bids, keywords and creatives","Report on spend, leads and ROI every month"],
   faqs=[("What budget do I need for Google Ads in Goa?","It depends on your industry and goals; we start lean, prove ROI, then scale what works."),
         ("How fast do Google Ads work?","You can start getting clicks and leads within days of launch."),
         ("Will you manage the landing page too?","Yes — conversion-ready landing pages are part of how we lift results.")]),

 dict(n=4, slug="social-media-marketing-goa", cat="Social Media", loc="Goa",
   title="Social Media Marketing in Goa: Grow & Convert | Sanctify",
   h1="Social Media Marketing in Goa: Content, Community & Campaigns",
   excerpt="Social media marketing in Goa that builds reach, trust and sales — content, community management and paid campaigns on Instagram, Facebook and more.",
   img_alt="Young Indian woman creating social media content with a phone on a tripod in Goa",
   img_prompt=_img("trendy casual outfit", "filming a short social-media video on a phone mounted on a tripod with a ring light"),
   intro=["In Goa, Instagram and Facebook are where discovery happens — for cafes, salons, stays, events and shops. But posting randomly rarely works. A clear content and paid strategy does.",
          "Sanctify plans, creates and promotes content that turns followers into customers."],
   offers=[("Content creation","On-brand posts, stories and reels planned around your goals."),
           ("Community management","Replies, DMs and engagement that build loyal followers."),
           ("Paid social","Targeted Instagram and Facebook ads that drive reach and leads."),
           ("Analytics","Clear reporting on reach, engagement and conversions.")],
   why_h="Why social media matters in Goa",
   why="Goa's audience — locals, tourists and creators — discovers and shares brands on social first. Strong, consistent content builds trust before someone ever calls, while paid campaigns put you in front of exactly the right travellers and residents at the right time.",
   process=["Define brand voice and content pillars","Plan a monthly content calendar","Create posts, stories and reels","Run targeted paid campaigns","Review analytics and refine"],
   faqs=[("Which platforms should my Goa business use?","Usually Instagram and Facebook first; we add YouTube or others based on your audience."),
         ("How often should I post?","Consistency beats volume — a sustainable, planned cadence outperforms sporadic bursts."),
         ("Do you create the content too?","Yes, including reels, graphics and captions.")]),

 dict(n=5, slug="web-design-development-goa", cat="Web Design", loc="Goa",
   title="Web Design & Development in Goa: Fast, Converting Sites | Sanctify",
   h1="Web Design & Development in Goa: Fast, Mobile-First, Converting",
   excerpt="Professional web design and development in Goa — fast, mobile-first, conversion-ready websites that turn visitors into customers. By Sanctify.",
   img_alt="Young Indian woman web designer reviewing a website mockup on a large screen in Goa",
   img_prompt=_img("smart-casual outfit", "reviewing a colourful website design mockup on a large monitor in a creative studio"),
   intro=["Your website is often the first impression a customer has of your business. A slow, dated site loses trust in seconds; a fast, clear one turns visitors into enquiries.",
          "Sanctify designs and builds modern, mobile-first websites for Goa businesses — beautiful, quick and built to convert."],
   offers=[("Custom design","Tailored to your brand and audience, not a generic template."),
           ("Mobile-first & fast","Optimised for phones and Core Web Vitals."),
           ("Conversion-ready","Clear calls-to-action, enquiry forms and WhatsApp integration."),
           ("SEO foundations","Clean structure and speed that help you rank from day one.")],
   why_h="Why your Goa website matters",
   why="Most of your visitors are on mobile, often on patchy connections. A website that loads fast, reads clearly and makes it effortless to call, book or message you will out-perform a prettier but slower competitor every time.",
   process=["Discovery: goals, audience and content","Wireframe and design","Build, optimise and test","Launch with analytics and tracking","Support and iterate"],
   faqs=[("How long does a website take?","A typical business site takes a few weeks depending on pages and content."),
         ("Will my site work on mobile?","Yes — every site we build is mobile-first and speed-optimised."),
         ("Can you redesign my existing site?","Absolutely, while preserving your SEO and content.")]),

 dict(n=6, slug="branding-graphic-design-goa", cat="Branding", loc="Goa",
   title="Branding & Graphic Design in Goa | Sanctify",
   h1="Branding & Graphic Design in Goa: Stand Out and Be Remembered",
   excerpt="Branding and graphic design in Goa — logos, identity and creatives that make your business look professional and memorable. By Sanctify.",
   img_alt="Young Indian woman graphic designer with brand colour swatches and a tablet in Goa",
   img_prompt=_img("stylish casual outfit", "at a design desk with brand colour swatches, a tablet and logo sketches"),
   intro=["A strong brand makes you look established, trustworthy and worth the price. A weak or inconsistent one quietly costs you customers.",
          "Sanctify builds distinctive brand identities for Goa businesses — from logo to full visual system."],
   offers=[("Logo & identity","A memorable logo and complete visual identity."),
           ("Brand guidelines","Colours, fonts and usage that keep you consistent everywhere."),
           ("Marketing creatives","Brochures, flyers, menus, hoardings and social templates."),
           ("Packaging & print","Design that looks premium on shelf and in hand.")],
   why_h="Why branding pays off in Goa",
   why="In a market full of choices, people buy from brands that look confident and consistent. Cohesive branding across your storefront, social, packaging and website builds instant recognition and lets you charge what you're worth.",
   process=["Discover your positioning and audience","Design logo and core identity","Create brand guidelines","Roll out across touchpoints","Hand over editable assets"],
   faqs=[("What's included in a brand identity?","Typically a logo suite, colour palette, typography and usage guidelines, plus key creatives."),
         ("Can you refresh my existing brand?","Yes — we can evolve your look while keeping the equity you've built."),
         ("Do you design print and packaging?","Yes, from menus and flyers to packaging and signage.")]),

 dict(n=7, slug="video-reels-marketing-goa", cat="Video & Reels", loc="Goa",
   title="Video & Reels Marketing in Goa: Get Seen | Sanctify",
   h1="Video & Reels Marketing in Goa: Scroll-Stopping Content That Converts",
   excerpt="Scroll-stopping video and reels marketing in Goa that builds reach, trust and engagement across Instagram, YouTube and more. By Sanctify.",
   img_alt="Young Indian woman recording a reel on a smartphone at a scenic Goa location",
   img_prompt=_img("trendy casual college outfit", "recording a vertical reel on a smartphone at a bright, scenic outdoor spot"),
   intro=["Short video is the fastest way to grow reach in Goa right now. Reels and YouTube Shorts routinely out-perform static posts for discovery.",
          "Sanctify produces scroll-stopping video and reels that get your brand seen, trusted and shared."],
   offers=[("Reels & shorts","Fast, on-trend vertical videos designed to be watched to the end."),
           ("Concept & scripting","Hooks and ideas that stop the scroll."),
           ("Shoot & edit","Professional filming and snappy edits."),
           ("Distribution","Posting and promotion for maximum reach.")],
   why_h="Why reels win in Goa",
   why="Goa is one of India's most photogenic markets — food, stays, beaches, events. Video captures that energy and travels far on the algorithm, putting your brand in front of tourists planning their trip and locals looking for what's new.",
   process=["Plan monthly video concepts","Script and shoot","Edit with captions and music","Publish and promote","Measure watch-time and reach"],
   faqs=[("How many reels per month?","We recommend a sustainable cadence based on your goals and budget."),
         ("Do you shoot on location in Goa?","Yes — on-location and in-studio, depending on the concept."),
         ("Can you repurpose one shoot into many clips?","Yes, we maximise every shoot into multiple pieces.")]),

 dict(n=8, slug="online-reputation-management-goa", cat="Reputation", loc="Goa",
   title="Online Reputation Management in Goa | Sanctify",
   h1="Online Reputation Management in Goa: Protect and Build Trust",
   excerpt="Online reputation management in Goa — monitor reviews, respond professionally and build a trustworthy brand image. By Sanctify.",
   img_alt="Young Indian woman managing online reviews on a tablet in a Goa office",
   img_prompt=_img("professional smart-casual outfit", "reviewing customer reviews and ratings on a tablet at a tidy desk"),
   intro=["A handful of unanswered negative reviews can quietly sink your bookings. In hospitality-heavy Goa, reputation is revenue.",
          "Sanctify helps you monitor, manage and grow a positive online reputation across Google, social and review sites."],
   offers=[("Review monitoring","Know what's being said about you, everywhere."),
           ("Response management","Professional, on-brand replies to reviews and comments."),
           ("Review generation","Ethical systems to earn more genuine positive reviews."),
           ("Crisis support","Calm, strategic handling of negative situations.")],
   why_h="Why reputation matters in Goa",
   why="Travellers and locals read reviews before they call. A strong star rating and thoughtful responses signal that you care — often the deciding factor between you and the place next door.",
   process=["Audit your current reviews and ratings","Set up monitoring and alerts","Respond consistently and professionally","Encourage happy customers to review","Report on rating trends"],
   faqs=[("Can you remove fake negative reviews?","We help report policy-violating reviews and, more importantly, drown them out with genuine positive ones."),
         ("How do you get more positive reviews?","With simple, ethical prompts to real, satisfied customers."),
         ("Which platforms do you cover?","Google, Facebook, and industry sites relevant to your business.")]),

 dict(n=9, slug="influencer-marketing-pr-goa", cat="Influencer & PR", loc="Goa",
   title="Influencer Marketing & PR in Goa | Sanctify",
   h1="Influencer Marketing & PR in Goa: Reach Engaged Audiences",
   excerpt="Influencer marketing and PR in Goa — creator partnerships and press coverage that put your brand in front of engaged Goan and travel audiences. By Sanctify.",
   img_alt="Young Indian woman content creator at a Goa cafe creating branded content",
   img_prompt=_img("stylish casual outfit", "at a trendy cafe creating branded lifestyle content with a phone and coffee"),
   intro=["The right Goa creator can introduce your brand to thousands of engaged, local and travelling followers in a single, authentic post.",
          "Sanctify runs influencer partnerships and PR campaigns that build reach and trust — including celebrity-led campaigns."],
   offers=[("Creator partnerships","Matched to your audience and budget, from micro to macro."),
           ("Campaign management","Briefs, deliverables and coordination handled end-to-end."),
           ("Press & PR","Professionally written releases distributed to news and media."),
           ("Celebrity endorsement","Connect your brand with the right celebrity face.")],
   why_h="Why influencer marketing works in Goa",
   why="Goa is a magnet for creators and travel content. Partnering with the right voices puts your cafe, stay, event or product directly in front of people already planning to visit or spend — with the credibility of a trusted recommendation.",
   process=["Define goals and audience","Shortlist and vet creators","Brief and manage the campaign","Amplify the best content with ads","Report on reach and results"],
   faqs=[("Do micro-influencers work?","Often better than big names — engaged niche audiences convert well and cost less."),
         ("Can you get press coverage?","Yes, through professionally written and distributed releases."),
         ("Do you handle celebrity campaigns?","Yes, including endorsement and end-to-end celebrity management.")]),

 # ---------- Location / industry posts ----------
 dict(n=10, slug="digital-marketing-agency-panaji", cat="Digital Marketing", loc="Panaji",
   title="Digital Marketing Agency in Panaji, Goa | Sanctify",
   h1="Digital Marketing Agency in Panaji: Grow Your Business Online",
   excerpt="Looking for a digital marketing agency in Panaji? Sanctify offers SEO, Google Ads, social media, web design and branding for Panaji businesses.",
   img_alt="Young Indian woman marketing professional near a Panaji landmark with a laptop bag",
   img_prompt=_img("professional blazer and smart trousers", "walking confidently in a clean city street setting with a laptop bag"),
   intro=["Panaji is Goa's capital and commercial heart — which means competition for attention is high. Standing out online takes strategy, not guesswork.",
          "Sanctify is a full-service digital marketing agency working with Panaji businesses across retail, hospitality, services and real estate."],
   offers=[("Local SEO for Panaji","Rank for 'near me' and 'in Panaji' searches."),
           ("Google Ads","Instant, targeted leads from ready-to-buy searchers."),
           ("Social media","Content and campaigns tuned to Panaji's audience."),
           ("Websites & branding","Fast sites and identities that build trust.")],
   why_h="Why Panaji businesses choose Sanctify",
   why="From the shops around 18th June Road to offices and restaurants across the city, Panaji customers search online before they visit. A local, strategy-led partner who understands the Goan market helps you capture that demand — with transparent reporting on what's working.",
   process=["Audit your online presence","Prioritise quick wins and long-term SEO","Launch ads and social","Improve website and conversions","Report monthly on leads"],
   faqs=[("Do you work with small Panaji businesses?","Yes — we tailor plans for shops, clinics, cafes and startups, not just big brands."),
         ("Where is Sanctify based?","We're a Goa agency (Vasco-da-Gama) working across Panaji and all of Goa."),
         ("How do we start?","Book a free consultation via call or WhatsApp on +91 99233 52923.")]),

 dict(n=11, slug="seo-company-margao", cat="SEO", loc="Margao",
   title="SEO Company in Margao, Goa: Rank & Get Leads | Sanctify",
   h1="SEO Company in Margao: Get Found by South Goa Customers",
   excerpt="Sanctify is an SEO company serving Margao and South Goa — keyword research, on-page, technical and local SEO that grows organic leads.",
   img_alt="Young Indian woman analysing search rankings on a laptop for a Margao business",
   img_prompt=_img("smart-casual blazer", "analysing search-ranking graphs on a laptop in a bright office"),
   intro=["Margao is South Goa's busy commercial hub — and its customers turn to Google first. If you're not on page one, you're invisible to them.",
          "Sanctify helps Margao businesses rank for the searches that bring real leads."],
   offers=[("Margao keyword research","Target what South Goa customers actually search."),
           ("On-page & technical SEO","A fast, well-structured, crawlable site."),
           ("Local SEO","Map Pack visibility for Margao 'near me' searches."),
           ("Content & links","Authority that lifts rankings over time.")],
   why_h="Why SEO wins in Margao",
   why="Margao's mix of retail, services and offices means steady, year-round search demand. Ranking well captures that demand without paying per click — a durable advantage over competitors who rely only on ads.",
   process=["Rankings and competitor audit","Keyword and content plan","Fix technical and on-page issues","Build local signals and links","Monthly reporting"],
   faqs=[("How soon will I rank in Margao?","Local terms can move in weeks; competitive terms take a few months of consistent work."),
         ("Do you cover all of South Goa?","Yes — Margao, Fatorda, Colva, Benaulim and nearby areas."),
         ("Is local SEO included?","Yes, including Google Business Profile optimisation.")]),

 dict(n=12, slug="social-media-marketing-vasco", cat="Social Media", loc="Vasco-da-Gama",
   title="Social Media Marketing in Vasco-da-Gama | Sanctify",
   h1="Social Media Marketing in Vasco-da-Gama: Reach Local Customers",
   excerpt="Social media marketing in Vasco-da-Gama — content, reels and paid campaigns that grow your local audience and sales. By Sanctify.",
   img_alt="Young Indian woman filming social content near a Vasco-da-Gama shopfront",
   img_prompt=_img("trendy casual outfit", "filming lifestyle content on a phone near a bright local shopfront"),
   intro=["Vasco is a fast-moving port city with loyal local customers — and social media is where they discover new shops, salons and eateries.",
          "Sanctify, based right here in Vasco-da-Gama, helps local businesses grow with content and paid campaigns that actually convert."],
   offers=[("Local content","Reels and posts that speak to Vasco's audience."),
           ("Paid social","Geo-targeted ads to reach nearby customers."),
           ("Community management","Engagement that builds loyal regulars."),
           ("Offers & campaigns","Promotions that drive footfall.")],
   why_h="Why Vasco businesses trust Sanctify",
   why="As a Vasco-based agency, we understand the local audience and seasons. Consistent, locally-relevant social content keeps your business top-of-mind and turns followers into walk-ins and repeat customers.",
   process=["Set goals and brand voice","Plan a local content calendar","Create reels, posts and stories","Run geo-targeted ads","Review and optimise"],
   faqs=[("Are you located in Vasco?","Yes — Sanctify is based in Vasco-da-Gama, serving all of Goa."),
         ("Can you run offers for my shop?","Yes, we design and promote local offers and campaigns."),
         ("Do you make the content?","Yes, including reels, graphics and captions.")]),

 dict(n=13, slug="web-design-mapusa", cat="Web Design", loc="Mapusa",
   title="Web Design in Mapusa, North Goa | Sanctify",
   h1="Web Design in Mapusa: Modern, Fast Websites for North Goa",
   excerpt="Web design in Mapusa — fast, mobile-first, conversion-ready websites for North Goa businesses. Designed and built by Sanctify.",
   img_alt="Young Indian woman presenting a website design on a laptop for a Mapusa business",
   img_prompt=_img("smart-casual outfit", "presenting a website design on a laptop to a client across a table"),
   intro=["Mapusa's markets and businesses draw customers from across North Goa. A modern website helps you convert that interest into calls and visits.",
          "Sanctify designs fast, mobile-first websites for Mapusa businesses — built to look great and convert."],
   offers=[("Custom, mobile-first design","Looks great on the phones your customers use."),
           ("Speed & SEO","Fast pages that rank and retain visitors."),
           ("Enquiry & WhatsApp","Make it effortless to contact you."),
           ("Easy to update","Simple content management and support.")],
   why_h="Why Mapusa businesses need a strong website",
   why="Customers researching a shop, service or clinic in Mapusa will judge you by your website in seconds. A quick, clear, mobile-first site builds trust and turns browsers into buyers.",
   process=["Plan pages and content","Design and review","Build and optimise","Launch with tracking","Support and improve"],
   faqs=[("How much does a website cost in Mapusa?","It depends on pages and features; we scope to your goals and budget."),
         ("Do you provide hosting?","Yes, we can arrange fast, reliable hosting."),
         ("Can you add online enquiries?","Yes — forms, WhatsApp and click-to-call are standard.")]),

 dict(n=14, slug="google-ads-hotels-calangute", cat="Google Ads", loc="Calangute",
   title="Google Ads for Hotels in Calangute, Goa | Sanctify",
   h1="Google Ads for Hotels in Calangute: Fill More Rooms",
   excerpt="Google Ads for hotels and resorts in Calangute — capture direct bookings and reduce OTA commissions with ROI-focused PPC by Sanctify.",
   img_alt="Young Indian woman travel marketer planning hotel ads on a laptop near a Calangute beach setting",
   img_prompt=_img("light summer smart-casual outfit", "working on a laptop at a bright beachside cafe table planning campaigns"),
   intro=["Calangute is one of Goa's most competitive hospitality markets. Every night an empty room is revenue you never get back.",
          "Sanctify runs Google Ads for Calangute hotels and resorts to drive direct bookings and cut reliance on high-commission OTAs."],
   offers=[("Direct-booking search ads","Capture 'hotels in Calangute' searches."),
           ("Remarketing","Bring back visitors who didn't book."),
           ("Seasonal scaling","Ramp up for peak season, pause in lulls."),
           ("Booking tracking","Measure cost per booking, not just clicks.")],
   why_h="Why hotels in Calangute use PPC",
   why="Travellers plan trips on Google and OTAs. Well-run search and remarketing ads help you win direct bookings — keeping the commission you'd otherwise pay a platform, and giving you the guest relationship.",
   process=["Set target cost per booking","Build search and remarketing campaigns","Create a fast booking landing page","Optimise by season and demand","Report on bookings and ROI"],
   faqs=[("Can ads reduce my OTA commissions?","Yes — driving direct bookings means you keep more of every booking."),
         ("Is this only for big hotels?","No — boutique stays and guesthouses benefit too."),
         ("What about peak season?","We scale spend to match demand and pause in off-season.")]),

 dict(n=15, slug="digital-marketing-restaurants-candolim", cat="Digital Marketing", loc="Candolim",
   title="Digital Marketing for Restaurants in Candolim | Sanctify",
   h1="Digital Marketing for Restaurants in Candolim: Fill More Tables",
   excerpt="Digital marketing for restaurants and cafes in Candolim — local SEO, reels, reviews and ads that fill tables. By Sanctify.",
   img_alt="Young Indian woman food content creator photographing a dish at a Candolim restaurant",
   img_prompt=_img("stylish casual outfit", "photographing an appetising plated dish at a bright restaurant table"),
   intro=["In Candolim, diners choose where to eat on Instagram and Google — often minutes before they arrive. Great food isn't enough if they can't find you.",
          "Sanctify helps Candolim restaurants and cafes get discovered and fill tables with local SEO, mouth-watering content and smart ads."],
   offers=[("Local SEO & Maps","Show up for 'restaurants in Candolim' and 'near me'."),
           ("Food reels & photography","Appetising content that drives cravings and visits."),
           ("Reviews","Earn and manage the ratings diners trust."),
           ("Offers & ads","Promote events, happy hours and specials.")],
   why_h="Why Candolim restaurants need digital marketing",
   why="Candolim's dining scene is crowded and seasonal. Strong visuals, high ratings and Map Pack visibility mean hungry tourists and locals pick you first — and come back.",
   process=["Optimise Google Business Profile","Shoot food reels and photos","Build a reviews flow","Run local offers and ads","Track calls, directions and covers"],
   faqs=[("Do you shoot food photography?","Yes — appetising, professional photography and reels are a specialty."),
         ("Can you help with festival/season pushes?","Yes, we plan campaigns around peak periods and events."),
         ("How do we get more reviews?","With simple, ethical prompts to happy diners.")]),

 dict(n=16, slug="seo-real-estate-porvorim", cat="SEO", loc="Porvorim",
   title="SEO for Real Estate in Porvorim, Goa | Sanctify",
   h1="SEO for Real Estate in Porvorim: Get Found by Serious Buyers",
   excerpt="SEO for real estate agents and builders in Porvorim — rank for property searches and generate qualified buyer and NRI leads. By Sanctify.",
   img_alt="Young Indian woman real-estate marketer reviewing property listings on a laptop in Porvorim",
   img_prompt=_img("professional blazer", "reviewing property listings and analytics on a laptop in a modern office"),
   intro=["Property buyers — including NRIs — research online for weeks before they enquire. If your listings don't rank, you lose them to portals and competitors.",
          "Sanctify helps Porvorim real estate agents and developers rank for high-intent property searches and capture qualified leads."],
   offers=[("Property keyword SEO","Rank for 'flats in Porvorim', 'villas in North Goa' and more."),
           ("Local & project pages","Optimised pages for each project and location."),
           ("Lead capture","Enquiry forms and WhatsApp that convert."),
           ("Content authority","Guides that build trust with buyers.")],
   why_h="Why real estate SEO works in Porvorim",
   why="Porvorim is a prime North Goa property corridor with strong NRI and investor interest. High-intent buyers search specific terms; ranking for them delivers leads that are far cheaper and warmer than cold outreach.",
   process=["Research buyer search terms","Build optimised project/location pages","Improve site speed and structure","Publish helpful buyer guides","Report on rankings and leads"],
   faqs=[("Can you generate NRI leads?","Yes — we target the searches and content NRIs use when buying in Goa."),
         ("Do you build project microsites?","Yes, fast landing pages per project are available."),
         ("Is SEO better than portals?","It complements them — your own ranked pages mean leads without per-lead portal fees.")]),

 dict(n=17, slug="social-media-cafes-anjuna", cat="Social Media", loc="Anjuna",
   title="Social Media for Cafes in Anjuna, Goa | Sanctify",
   h1="Social Media for Cafes in Anjuna: Turn Scrolls into Footfall",
   excerpt="Social media marketing for cafes in Anjuna — reels, aesthetics and campaigns that turn Instagram scrolls into footfall. By Sanctify.",
   img_alt="Young Indian woman creating aesthetic cafe content on a phone in Anjuna",
   img_prompt=_img("boho casual outfit", "creating aesthetic content on a phone at a stylish, plant-filled cafe"),
   intro=["Anjuna runs on aesthetics and discovery — travellers pick cafes straight from their Instagram feed and Reels.",
          "Sanctify helps Anjuna cafes build a scroll-stopping presence that converts followers into footfall."],
   offers=[("Aesthetic content","Feed and reels that match Anjuna's vibe."),
           ("Reels strategy","Discovery-focused video that reaches travellers."),
           ("Influencer collabs","Creator partnerships that drive visits."),
           ("Geo-targeted ads","Reach tourists near Anjuna and North Goa.")],
   why_h="Why Anjuna cafes need social media",
   why="In Anjuna, your Instagram is your storefront. A cohesive, beautiful feed and strong reels are what make a traveller screenshot your location and walk in that evening.",
   process=["Define a signature aesthetic","Plan reels and feed","Collaborate with creators","Run geo-targeted ads","Track saves, shares and visits"],
   faqs=[("Do you work with small cafes?","Yes — plans scale to independent cafes and shacks."),
         ("Can you connect us with influencers?","Yes, matched to your vibe and budget."),
         ("How fast can we grow?","Reels can drive quick discovery; consistency compounds it.")]),

 dict(n=18, slug="digital-marketing-beauty-salons-goa", cat="Digital Marketing", loc="Goa",
   title="Digital Marketing for Beauty Salons in Goa | Sanctify",
   h1="Digital Marketing for Beauty Salons & Spas in Goa",
   excerpt="Digital marketing for beauty salons and spas in Goa — local SEO, reels, reviews and bookings that fill your calendar. By Sanctify.",
   img_alt="Young Indian woman salon client showing a fresh hairstyle for social content in Goa",
   img_prompt=_img("chic casual outfit", "smiling in a bright modern salon showing a fresh, stylish hairstyle"),
   intro=["Salons and spas live and die by local discovery and reviews. When someone searches 'salon near me' in Goa, you want to be the first they call.",
          "Sanctify helps Goa salons and spas fill their calendars with local SEO, beautiful content and bookings."],
   offers=[("Local SEO & Maps","Top the 'salon near me' results in your area."),
           ("Before/after reels","Show off transformations that book clients."),
           ("Reviews & bookings","Earn ratings and make booking effortless."),
           ("Offers & ads","Promote packages, bridal and seasonal offers.")],
   why_h="Why salons in Goa need digital marketing",
   why="Beauty is visual and local. Strong photos and reels of your work, high ratings and easy booking turn nearby searchers into loyal, repeat clients — especially for bridal and event season.",
   process=["Optimise Google Business Profile","Create before/after content","Set up bookings and reviews","Run local and bridal offers","Track calls and bookings"],
   faqs=[("Do you help with bridal season?","Yes — bridal and event campaigns are a great fit."),
         ("Can clients book online?","Yes, we set up simple booking and WhatsApp flows."),
         ("Is this affordable for a single salon?","Yes — we scale plans to independent salons.")]),

 dict(n=19, slug="marketing-tour-operators-goa", cat="Digital Marketing", loc="Goa",
   title="Marketing for Tour Operators & Activities in Goa | Sanctify",
   h1="Marketing for Tour Operators and Activities in Goa",
   excerpt="Digital marketing for tour operators, water sports and activity providers in Goa — ads, SEO and content that drive bookings. By Sanctify.",
   img_alt="Young Indian woman travel marketer planning tour promotions on a laptop in Goa",
   img_prompt=_img("light casual travel outfit", "planning travel promotions on a laptop at a bright seaside workspace"),
   intro=["Tourists book tours, cruises and water sports online — often on their phones after they land. If you're not visible, they book with whoever is.",
          "Sanctify helps Goa tour operators and activity providers capture bookings with ads, SEO and content built for travellers."],
   offers=[("Search & travel ads","Capture 'things to do in Goa' and activity searches."),
           ("SEO & content","Rank for tours, cruises and water-sports terms."),
           ("Reels & UGC","Show the experience to sell the experience."),
           ("Bookings","Fast landing pages and WhatsApp booking.")],
   why_h="Why tour operators in Goa need digital marketing",
   why="Travel is researched and booked online, often last-minute. Being visible on search and social at the planning moment — with vivid content and easy booking — is what turns interest into paid activities.",
   process=["Map traveller search demand","Run search and social ads","Build activity landing pages","Create experience reels","Track bookings and ROI"],
   faqs=[("Do you handle seasonal peaks?","Yes — we scale campaigns to match tourist season."),
         ("Can you promote water sports and cruises?","Yes, with video-led campaigns that sell the experience."),
         ("How do travellers book?","Via fast landing pages, forms and WhatsApp.")]),

 dict(n=20, slug="google-business-profile-clinics-panaji", cat="Local SEO", loc="Panaji",
   title="Google Business Profile for Clinics in Panaji | Sanctify",
   h1="Google Business Profile for Clinics & Doctors in Panaji",
   excerpt="Google Business Profile and local SEO for clinics and doctors in Panaji — get found for health searches and win more patient calls. By Sanctify.",
   img_alt="Young Indian woman clinic manager updating a Google Business Profile on a tablet in Panaji",
   img_prompt=_img("professional smart outfit", "updating a business profile on a tablet at a clean, modern clinic reception"),
   intro=["When someone needs a doctor, dentist or clinic in Panaji, they search Google and call one of the top results. Visibility here directly means patient calls.",
          "Sanctify optimises Google Business Profiles and local SEO for Panaji clinics so you're the one they find and trust."],
   offers=[("Profile optimisation","Services, hours, photos and categories done right."),
           ("Reviews & trust","Earn and manage patient reviews ethically."),
           ("Local SEO","Rank for treatments and 'near me' health searches."),
           ("Call tracking","See exactly how many calls you get.")],
   why_h="Why clinics in Panaji need local SEO",
   why="Health searches are urgent and local. A complete, well-reviewed Google Business Profile puts your clinic in the Map Pack at the moment patients decide who to call — often the difference between a full and empty appointment book.",
   process=["Optimise and verify the profile","Add services, photos and hours","Set up an ethical reviews flow","Improve local rankings","Report on calls and directions"],
   faqs=[("Is this compliant for healthcare?","Yes — we keep content accurate and professional, with ethical review practices."),
         ("Can multiple doctors be listed?","Yes, we structure profiles for clinics with multiple practitioners."),
         ("Do you track patient calls?","Yes, so you can see real results.")]),

 dict(n=21, slug="website-design-shops-margao", cat="Web Design", loc="Margao",
   title="Website Design for Shops & Retail in Margao | Sanctify",
   h1="Website Design for Shops and Retail in Margao",
   excerpt="Website design for shops and retail businesses in Margao — fast, mobile-first sites with catalogues, WhatsApp and enquiries. By Sanctify.",
   img_alt="Young Indian woman shop owner showing products online on a laptop in Margao",
   img_prompt=_img("smart-casual outfit", "showing a product catalogue on a laptop inside a bright retail shop"),
   intro=["Shoppers in Margao check online before they visit — for your range, prices, timings and location. A simple, fast website turns that curiosity into footfall and orders.",
          "Sanctify builds practical, mobile-first websites for Margao shops and retailers — with catalogues, WhatsApp ordering and enquiries."],
   offers=[("Product catalogue","Show your range clearly, updated easily."),
           ("WhatsApp ordering","Let customers enquire and order in one tap."),
           ("Mobile-first & fast","Built for the phones your customers use."),
           ("Local SEO","Get found for your products in Margao.")],
   why_h="Why Margao shops need a website",
   why="Even without full e-commerce, a clear website with your catalogue, location and WhatsApp makes it effortless for Margao customers to choose you — and drives both in-store visits and direct orders.",
   process=["Plan catalogue and pages","Design mobile-first","Build with WhatsApp and enquiries","Launch and optimise for local SEO","Support and update"],
   faqs=[("Do I need full e-commerce?","Not always — a catalogue with WhatsApp ordering is often enough to start."),
         ("Can customers order on WhatsApp?","Yes, one-tap WhatsApp enquiry and ordering is standard."),
         ("Can you update products for me?","Yes, or we make it simple for you to do it yourself.")]),
]

assert len(BLOGS) == 21, len(BLOGS)
assert len({b['slug'] for b in BLOGS}) == 21
